### ISSUE TITLE
Dark Mode doesn't work properly in Firefox

### ISSUE THREAD

**Issue by Thelta** [yursan9/manis-hugo-theme#23]
![Left is Firefox, Right is Chrome](https://i.imgur.com/obL8ada.jpg)
Left is Firefox, Right is Chrome

From it seems, Firefox doesn't invert background-color.  I made it work changing dark.css with below.
``` css
body {
    background-color: #141414 !important;
    margin: 0;
}
    
body {
    filter: invert(100%) hue-rotate(180deg);
}

img:not(.icon-text, .icon-social),
video,
code {
filter: invert(100%) hue-rotate(180deg) contrast(100%);
}

```
